### ISSUE TITLE
broken guard when weak upgraded to guard in spawned task

### ISSUE THREAD

**Issue by cameronbraid** [plabayo/tokio-graceful#6] opened 2023-12-02 03:15 UTC
First of all - thanks for this lib - I discovered it from `this week in rust` and I think its a simple and elegant solution to the graceful shutdown problem.

I have run into an issue where I upgade a weak guard in my app and the guard doesn't prevent the shutdown.

I created a standalone reproduction so that you can quickly verify that either I am doing something wrong (which could be likely) or if its an issue in your library

https://github.com/cameronbraid/tokio-graceful-spawn-broken-guard

Instructions from README 

Expected results :

```sh
cargo run --bin main
```

produces :

```
guard is set
Err(TimeoutError(1s))
```

Issue is when the guard is upgraded in a spawned task

```sh
cargo run --bin spawn
```

produces :

```
guard is set
Ok(14.999µs)
```

**Comment by GlenDC** [comment] 2023-12-03 09:21
Thank you for the report, kind words and providing the clean example. As it’s weekend I’m a bit slower to react.

I’ll look into it tonight for you. If there’s an issue I’ll probably patch it in the next 24h. I’ll either way come back to you within that timeframe with a status update.

Thank you once again for the report and take care!

**Comment by GlenDC** [comment] 2023-12-03 23:13
<img width="1723" alt="Screenshot 2023-12-04 at 00 04 12" src="https://github.com/plabayo/tokio-graceful/assets/3900482/10aaaa8d-3ef2-4fe3-a162-4fbc45a61e56">

If you enable tracing you can get some more info in your console to understand what is going on...

The problem is that when you spawn like you do it also means that you reach a state of zero reference count prior to upgrading. And once you have done that you are essentially already triggering the zero ref channel state. So despite upgrading indeed, you still will quit immediately as your trigger already has been triggered. With the main example you do not run into this issue because there you are awaiting your upgrade prior to shutting down.

```
shutdown.shutdown_with_limit
shutdown.shutdown
```

These 2 methods drop their own reference count prior to waiting. Meaning that if you call it while not having any guards active you are running intro trouble.

The thing is you are using the library in a pretty odd way. The entire goal was to not have to use mutexes where not needed, yet you wrap it into a mutex.

In general you shouldn't need any weak guard, unless you have a location where you want to wait cancellation but do not track it. This is however rare and I haven't needed it myself so far. What you really need is strong reference counts (most of the time).

I would hope the examples showcase this and how to use it. E.g. in https://github.com/plabayo/tokio-graceful/blob/main/examples/hyper.rs you can see that if you need to spawn (e.g. spawn your server/service), then it's easiest to do this via the `tokio-graceful` types as it will mean you create a guard for your spawned task. In case you have some kind of UDP/TCP Listener (or other stream receiver) you would then `select!` between whether you are cancelled or whether you receive something. If you receive something you can consume it further and else you can exit your loop and drop your guard. etc etc... (Note that these examples do have a minor footgun and that you probably want to store the cancelled guard instead, so you do not recreate that future each loop, but ok, minor detail).

Can you high level explain me how you plan to use `tokio-graceful` as I don't mind to help you by explaining how you should use this lib to achieve your goal. Going to close this ticket, as it is not a bug or something I need to fix. But that said, feel free to continue to talk here (or on discord) in case you have follow-up questions or something else.

**Closed as completed by GlenDC** 2023-12-03 23:13 UTC

**Comment by cameronbraid** [comment] 2023-12-04 00:03
Thanks for taking the time to identify the cause and give such a detailed explanation.

My high level requirement is to create shutdown guards at any time in my app.  For example I trigger some task and wish to block shutdown until that task finishes.  

Since you can upgrade a weak guard, I was assuming that the upgraded guard would block the shutdown,  and therefore the weak guard was a handle that I can use to create strong guards on demand.

**Comment by cameronbraid** [comment] 2023-12-04 00:16
fyi I updated my repro to make this clear

**Comment by GlenDC** [comment] 2023-12-04 08:49
Hi as discussed on Discord that is indeed more the approach you should take.
In fact you can improve your latest spawn example even more:

```rust
#![allow(clippy::print_stdout)]
use std::time::Duration;

#[tokio::main(flavor = "multi_thread")]
pub async fn main() {
    let shutdown = tokio_graceful::Shutdown::new(tokio::time::sleep(Duration::from_millis(10)));

    // my app will spawn tasks that wish to block shutdown
    // when none of these tasks are running, shutdown should proceed normally

    // attaches a guard to the lifespan of this task
    shutdown.spawn_task(async move {
        // create a strong guard to block shutdown
        println!("Doing work");
        tokio::time::sleep(Duration::from_secs(2)).await;
        println!("Done working");
    });

    // or optionally also get ownership of that guard
    shutdown.spawn_task_fn(|guard| async move {
        // this is useful for two reasons:
       // 1. because you want to exit in case of `guard.cancelled().await`
       // 2. or because you want to pass the guard further down your pipeline or into other (child*) tasks

       // this is to not re-create a cancelled future every loop cycle, but more of an unfortunate detail that surfaces
       // due to not having something like `merge!` available that would handle that for you
       // instead of `select!` which doesn't
       let mut cancelled_fut = guard.cancelled();
       tokio::pin!(cancelled_fut);

       loop {
             // (1)
             _ = cancelled_fut.as_mut() => {
                    println!("graceful shutdown triggered, exiting task");
                    break;
            }
            job = recv_job() => {
                  // (2)
                 guard.spawn(do_work(job));
           }
       }
    });

    println!(
        "{:?}",
        shutdown.shutdown_with_limit(Duration::from_secs(5)).await
    );
}
```

I would have hoped this is clear from the Examples and README. If not the case ,can you maybe help me figuring out how to make it more clear, the intended way to use the library and how to do so, etc..

Also is it all good for you now? Working? Understanding?
